public class MyTestingClass {
    private int x;
    private int y;

    // Constructor
    public MyTestingClass(int x, int y) {
        this.x = x;
        this.y = y;
    }

    // Custom hashCode method based on x and y coordinates
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + x;
        result = prime * result + y;
        return result;
    }

    // Equals method (generated by IDE for simplicity)
    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null || getClass() != obj.getClass())
            return false;
        MyTestingClass other = (MyTestingClass) obj;
        return x == other.x && y == other.y;
    }
}
